name: TITAN_MISSION
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to scan'
        required: true
        default: 'example.com'
jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Exec Nuclei
        run: |
          export PATH=$PATH:/home/infuselink/bin
          nuclei -u ${{ github.event.inputs.target }} -o results.txt
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: results.txt
